### ISSUE TITLE
禁止权限命名空间使用空格

### ISSUE THREAD

**Issue by 45gfg9** [mamoe/mirai-console#202]
```kotlin
@AutoService(JvmPlugin::class)
object Watcher : KotlinPlugin(
    JvmPluginDescription(
        "net.im45.bot.grw",
        "1.0.0-dev01",
        "GitHub Release Watcher"
    )
) {
```

```
> permission listpermissions
（无关权限略去）
plugin.github release watcher:*
```

```
> permission permit u* plugin.github release watcher:*
2020-10-07 12:33:04 E/console: net.mamoe.mirai.console.command.description.CommandArgumentParserException: 无法解析 plugin.github 为 PermissionId
```

**Comment by Karlatemp** [comment]
那就不要附加空格

**Comment by 45gfg9** [comment]
为什么要用name做权限节点名称呢
如果用id 或者让用户自己提供节点名称呢

**Comment by Him188** [comment]
应该使用 id, 这属于一处错误

**Comment by Karlatemp** [comment]
fixed by https://github.com/mamoe/mirai-console/commit/ab5f9f5ceecb4628999b1defaf99facd9d268677#diff-1f80c7f6b8f97385ebf0eab11524e9ee2eff1ea639821d986f75b7739a6b6190R157


for mamoe:

https://github.com/mamoe/mirai-console/blob/ab5f9f5ceecb4628999b1defaf99facd9d268677/backend/mirai-console/src/main/kotlin/net/mamoe/mirai/console/permission/PermissionService.kt#L152-L159

`plugin.name` 替换成 `plugin.id`
