### ISSUE TITLE
Auto update not necessary

### ISSUE THREAD

**Issue by saeziae** [mamoe/mirai-console#30]
While I do love a new version,  it is really unnecessary to update automatically (and forced), it is better to remind the user during startup and limit the timeout, but not to do it itself. And, when there is an error during auto-update like `Failed to fetch newest version`, it affects the the following running.

**Comment by liujiahua123123** [comment]
Since Mirai is under the fast-moving stage, it is necessary for auto-update. If there are API changes, we do NOT want to carry the deprecates APIs with few versions at this stage.

There are no reasons except your local network issue for Failed to "fetch the newest version" since we are using JCenter as version API. 

Besides, there are protocol changes, which may danger to your BOT account, you do NOT want to use wrong protocols which may cause problems to ur account safety.

Finally, the stable version, 1.0.0 is coming, at that time, there will be no force hot-update, I understand the process is torture, but it's all necessary
